CREATE DATABASE demo CHARSET utf8mb4;

USE demo;

CREATE TABLE article(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
title VARCHAR(50) UNIQUE NOT NULL,
`description` TEXT NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
category_id INT
)ENGINE=InnoDB;

CREATE TABLE category(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
category_name VARCHAR(50) UNIQUE NOT NULL
)ENGINE=InnoDB;

CREATE TABLE `account`(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
firstname VARCHAR(50) NOT NULL,
lastname VARCHAR(50) NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
`password` VARCHAR(100) NOT NULL
)ENGINE=InnoDB;

ALTER TABLE article
ADD CONSTRAINT fk_completed_category
FOREIGN KEY(category_id)
REFERENCES category(id);